swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    Poc

  version: production
basePath: /
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
      
tags:
  - description: <a href=https://evil.com>Click Here</a>
    name: accounts
   